### PR TITLE
chore: update documentation for registry to be in line with other providers

### PR DESCRIPTION
**Pull request by hedenface**
* changed registry docs to use Argument Reference and Attribute Reference
* added import block statement for tf 1.5.0+

### CODE REVIEW

**Comment by anitarua** [comment]
Hey @hedenface, thanks for submitting this PR!

The changes make sense and look great, but it looks like they're clashing with the changes made by [tfplugindocs](https://github.com/hashicorp/terraform-plugin-docs) when `go generate` is called in our GitHub Actions workflow.

It would be great to include these changes in these docs as well as any additional ones in the future. I think to do that, we'll need to create a [tfplugindocs template](https://github.com/hashicorp/terraform-plugin-docs?tab=readme-ov-file#templates). After that, I think running `go generate` in CI and locally would produce the same set of docs.

Would you be up for sketching out those templates? If not, I could take a stab at it.

Side note: don't worry about the Terraform Provider Acceptance tests for now; I expect them to fail until I pull your commits into a different branch in this repo due to how we had set up our workflows.

**Comment by hedenface** [comment]
yeah i can take a look at that

**Comment by hedenface** [comment]
No I'll just close this. Looking into the tfplugindocs templates, there doesn't appear to be an easy way to break it out into what appears to be the more common documentation standard. So, the level of effort would be a lot higher than I'm willing to spend at the moment.

**Comment by anitarua** [comment]
Alright. Thanks for bringing this docs discrepancy to our attention though!

**Pull request closed without merging**
